### ISSUE TITLE
Harvard medical dataset

### ISSUE THREAD

**Issue by zhaoym55** [Lizhe1228/MambaDFuse#1]
Can you share the train\test\val file of the Harvard medical dataset?

**Comment by zhaoym55** [comment]
是否能分享一下医学数据集的划分呢？（这个医学数据集划分是统一的还是自己随机划分的）？

**Comment by Lizhe1228** [comment]
据我所知，还没有统一划分的医学数据集，我们所选取的主要来自于，Harvard medical dataset网站上Alzheimer's disease、cavernous angioma、glioma with a tour、lyme这几种疾病。

**Comment by zhaoym55** [comment]
能否分享一下你们下载的数据集吗？万分感谢，这个网站不知道怎么下载


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lizhe1228/MambaDFuse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1)





 
据我所知，还没有统一划分的医学数据集，我们所选取的主要来自于，Harvard medical dataset网站上Alzheimer's disease、cavernous angioma、glioma with a tour、lyme这几种疾病。

**Comment by Lizhe1228** [comment]
> 能否分享一下你们下载的数据集吗？万分感谢，这个网站不知道怎么下载
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Lizhe1228/MambaDFuse" ***@***.***&gt;; 发送时间:&nbsp;2024年4月29日(星期一) 下午4:41 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1) 据我所知，还没有统一划分的医学数据集，我们所选取的主要来自于，Harvard medical dataset网站上Alzheimer's disease、cavernous angioma、glioma with a tour、lyme这几种疾病。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

对于这个数据集的下载，我也并没有找到简便的方式，我采取的方式是最笨的方式，一张张图片单独下载哈哈哈哈哈哈哈哈。对于我们所下载的数据集，目前还并没有计划准备公开。

**Comment by zhaoym55** [comment]
好的，感谢回复。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lizhe1228/MambaDFuse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1)





  
能否分享一下你们下载的数据集吗？万分感谢，这个网站不知道怎么下载
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Lizhe1228/MambaDFuse" @.&gt;; 发送时间:&nbsp;2024年4月29日(星期一) 下午4:41 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1) 据我所知，还没有统一划分的医学数据集，我们所选取的主要来自于，Harvard medical dataset网站上Alzheimer's disease、cavernous angioma、glioma with a tour、lyme这几种疾病。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
对于这个数据集的下载，我也并没有找到简便的方式，我采取的方式是最笨的方式，一张张图片单独下载哈哈哈哈哈哈哈哈。对于我们所下载的数据集，目前还并没有计划准备公开。

**Comment by Lizhe1228** [comment]
祝科研顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lizhe1228/MambaDFuse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1)





 好的，感谢回复。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Lizhe1228/MambaDFuse"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年4月29日(星期一) 下午4:49 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1) 
 
 
 
 
 
    
 能否分享一下你们下载的数据集吗？万分感谢，这个网站不知道怎么下载 
  … 
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "Lizhe1228/MambaDFuse" @.&amp;gt;; 发送时间:&amp;nbsp;2024年4月29日(星期一) 下午4:41 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [Lizhe1228/MambaDFuse] Harvard medical dataset (Issue #1) 据我所知，还没有统一划分的医学数据集，我们所选取的主要来自于，Harvard medical dataset网站上Alzheimer's disease、cavernous angioma、glioma with a tour、lyme这几种疾病。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;gt; 
    
 对于这个数据集的下载，我也并没有找到简便的方式，我采取的方式是最笨的方式，一张张图片单独下载哈哈哈哈哈哈哈哈。对于我们所下载的数据集，目前还并没有计划准备公开。
